name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zero-bank-tests_sof:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4 for Node.js 20 compatibility

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Updated to v4 for Node.js 20 compatibility
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: yarn playwright install firefox

      - name: Run Playwright Tests (Firefox)
        env:
          CI: true
        run: |
          set -e # Exit on any error
          yarn playwright test --project=firefox || true # Continue even if some tests fail

      - name: Upload Test Report
        if: always() # Ensure this runs regardless of test outcome
        uses: actions/upload-artifact@v4 # Updated to v4 for Node.js 20 compatibility
        with:
          name: playwright-report
          path: playwright-report/
